### PR TITLE
Allow for different search strings on each field

### PR DESCRIPTION
**Pull request by aaroncraig10e**
It's often useful to be able to do different search terms for different fields, such as `find all of the articles where the author's name includes "Jane" and the title contains "New York"`.

This PR allows for that sort of search.

### CODE REVIEW

**Comment by aaroncraig10e** [comment]
Just wanted to see if you're interested in PRs on this project.  We are currently in need of a robust front end search facility, and this project seems to tick a lot of boxes for us, however, we'd want to help out by building out some of the features.

Let me know if you are happy to accept PRs or not.  Thanks

**Comment by weixsong** [comment]
Hi, @aaroncraig10e , thanks for this PR, I was on vacation for a long time, just come back. Sorry for late reply. 
It's a good idea and thanks very much.

**Comment by weislanes** [comment]
Hi, any example of how to use this? In a little over my head trying to make it work. Thanks.

**Comment by aaroncraig10e** [comment]
@weislanes I ended up doing my own take on this, as we needed to move quickly.  https://github.com/10eTechnology/esjs

**Pull request merged**
