### PR TITLE
Code improvements - milestone

### PR DESCRIPTION
**Pull request by srenauld**
Think I'm at a final enough state to show the changes for  #102.

**Pipelines/tokens**:
- Tokens now have an (optional) array of metadata. This is used by the pipeline functions, for instance, to indicate token start and end positions for highlighting.
- The outward-facing API has been cleaned up so modules like `lunr-languages` can be used without any changes required to `elasticlunr`. A test is added to cover this use case
- There is now a possibility for each field to have its own pipeline. This is not enabled by default, but the `pipeline` option on the constructor of the `Index` class allows the user to do just that, should they wish to do so

**Index**:
- Completely new index class/logic. A class working as an adaptor is added on top to simplify the use of the library for now (in keeping the API consistent with elasticlunr 0.9.6)
- Additional query types and a true elasticsearch-like DSL, which all "old" query types convert to. This provides much, much more freedom in queries
- Highlighting! The results of a query can be fed almost straight back to `highlight()` to generate a curried function. From there, a second call to this with the start and end delimiters will yield a highlighted string:

```
    var results = idx.search({...}
    assert.equal(idx.highlight(results[0].ref, results[0].positions)('<i>', '</i>').body, "Mr. Green killed Colonel Mustard in the <i>study</i> with the candlestick. Mr. Green is not a very nice fellow.");
```

- Each field is now a separate, first-class citizen. This ties in with the pipeline change above, but also means that each field can now have its own settings when it comes to storing fragments, amongst other things
- Term matching at query time may now include regular expressions on a term-by-term basis, rather than having to define a wildcard/expansion match
- The export format for an index has changed. Old formats remain compatible for now. The new format takes advantage of the fact that, statistically, terms are likely to repeat between fields of the index, thus possibly providing a noticeable size decrease

**Usability/Developer experience**
- The build is no longer dependent on being on a *nix system and no longer requires `make`. The entirety of the build now leverages `webpack` and utilities present within the `npm` ecosystem
- Testing is reworked, now uses `mocha`+`chai`(+`sinon` for mocks). Every test is updated
- Most of the tests were focused on testing internal data structure instead of actually verifying contracts. All these tests have been updated and APIs formalized. In particular, the index and TF/IDF-related tests no longer check for inner object structure, prefering to rely on calls to functions instead
- Test coverage is massively improved. As of this PR we're on 90%+ on everything but branches

A few important notes:
- Due to the large number of added features, and the temporary need for the adaptor, the minified size of the library has increased. We're still below 10k gzipped so, while it is bigged, it isn't dangerously big
- The pipeline code is virtually unchanged, and could do with a touch-up

### CODE REVIEW

**Comment by srenauld** [comment]
@weixsong Did you have time to review any of this?

The bulk of the commit changes (marked by line changes) are changes from the doc, BTW. Actual changes is <1000 LoC on the library.

**Comment by smurrayatwork** [comment]
Pinging @weixsong for review, please.

**Comment by srenauld** [comment]
@weixsong Are you able to provide some feedback/review, or delegate to somebody else? There are three issues that could benefit from this.

**Comment by srenauld** [comment]
@smurrayatwork feels silly for @weixsong to have abandoned this project. I'll give it another month. if nothing moves by then I'm forking it.

**Comment by weixsong** [comment]
@srenauld , sorry for the late reply, I just don't have enough time to maintain this project, would you like to be administrator of this project to help maintain this project?

**Comment by liboz** [comment]
@srenauld Is there any plan to release a new version on npm in the near future?

**Pull request merged**
